services:
  postgres-miratech:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=miratech_db
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - '5432'
  server-miratech:
    image: mishaakamichael999/miratech-techtask
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      - postgres-miratech
