services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432'
  miratech-techtask:
    image: mishaakamichael999/miratech-techtask
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db-postgres
