spring:
  application:
    name: miratech-techtask
  datasource:
    password: postgres
    username: postgres
    url: 'jdbc:postgresql://postgres-miratech:5432/miratech_db?'
  jpa:
    hibernate:
      ddl-auto: none
