spring:
  application:
    name: miratech-techtask
  datasource:
    password: ${DB_PASSWORD}
    username: ${DB_USERNAME}
    url: 'jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?'
  jpa:
    hibernate:
      ddl-auto: none
