INSERT INTO task (title, description, status)
VALUES ('Complete Project Proposal', 'Write a detailed proposal for the upcoming project deadline', 'IN_PROGRESS'),
       ('Review Code Changes', 'Review and provide feedback on the latest code changes in the development branch',
        'PENDING'),
       ('Client Meeting Preparation',
        'Prepare presentation materials and agenda for the client meeting scheduled next week', 'TO_DO'),
       ('Bug Fixing', 'Investigate and fix the critical bug reported by the QA team', 'IN_PROGRESS'),
       ('Deploy Application Update', 'Deploy the latest application update to the staging environment for testing',
        'PENDING'),
       ('Prepare Project Proposal', 'Draft a detailed proposal outlining project scope and objectives', 'IN_PROGRESS'),
       ('Code Review for Feature X', 'Conduct a thorough review of the code changes related to Feature X', 'PENDING'),
       ('Client Meeting Agenda Creation',
        'Create an agenda for the upcoming client meeting to ensure smooth discussions', 'TO_DO'),
       ('Critical Bug Resolution',
        'Identify and resolve critical bugs reported by the QA team to ensure product stability', 'IN_PROGRESS'),
       ('Staging Environment Deployment',
        'Deploy the latest application update to the staging environment for testing and validation', 'PENDING');
